name: Deploy to EC2

on:
  push:
    branches:
      - main  
    # paths:
    #   - .github/workflows/deploy.yml
    #   - terraform/terraform_create.tf
      

      
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PRIVATE_KEY_BASE64: ${{ secrets.PRIVATE_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Terraform Init
        working-directory: terraform
        run: |
          terraform init -var="private_key_base64=${{ env.PRIVATE_KEY_BASE64 }}" -var="aws_access_key_id=${{ env.AWS_ACCESS_KEY_ID }}" -var="aws_secret_access_key=${{ env.AWS_SECRET_ACCESS_KEY }}"

      - name: Terraform Apply
        working-directory: terraform
        run: |
          terraform apply -auto-approve -var="private_key_base64=${{ env.PRIVATE_KEY_BASE64}}" -var="aws_access_key_id=${{ env.AWS_ACCESS_KEY_ID }}" -var="aws_secret_access_key=${{ env.AWS_SECRET_ACCESS_KEY }}"
      
      